package com.example.rumens.showtime.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.rumens.showtime.local.BeautyPhoto;
import com.example.rumens.showtime.local.NewsTypeInfo;
import com.example.rumens.showtime.local.VideoInfo;

import com.example.rumens.showtime.local.BeautyPhotoDao;
import com.example.rumens.showtime.local.NewsTypeInfoDao;
import com.example.rumens.showtime.local.VideoInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beautyPhotoDaoConfig;
    private final DaoConfig newsTypeInfoDaoConfig;
    private final DaoConfig videoInfoDaoConfig;

    private final BeautyPhotoDao beautyPhotoDao;
    private final NewsTypeInfoDao newsTypeInfoDao;
    private final VideoInfoDao videoInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beautyPhotoDaoConfig = daoConfigMap.get(BeautyPhotoDao.class).clone();
        beautyPhotoDaoConfig.initIdentityScope(type);

        newsTypeInfoDaoConfig = daoConfigMap.get(NewsTypeInfoDao.class).clone();
        newsTypeInfoDaoConfig.initIdentityScope(type);

        videoInfoDaoConfig = daoConfigMap.get(VideoInfoDao.class).clone();
        videoInfoDaoConfig.initIdentityScope(type);

        beautyPhotoDao = new BeautyPhotoDao(beautyPhotoDaoConfig, this);
        newsTypeInfoDao = new NewsTypeInfoDao(newsTypeInfoDaoConfig, this);
        videoInfoDao = new VideoInfoDao(videoInfoDaoConfig, this);

        registerDao(BeautyPhoto.class, beautyPhotoDao);
        registerDao(NewsTypeInfo.class, newsTypeInfoDao);
        registerDao(VideoInfo.class, videoInfoDao);
    }
    
    public void clear() {
        beautyPhotoDaoConfig.clearIdentityScope();
        newsTypeInfoDaoConfig.clearIdentityScope();
        videoInfoDaoConfig.clearIdentityScope();
    }

    public BeautyPhotoDao getBeautyPhotoDao() {
        return beautyPhotoDao;
    }

    public NewsTypeInfoDao getNewsTypeInfoDao() {
        return newsTypeInfoDao;
    }

    public VideoInfoDao getVideoInfoDao() {
        return videoInfoDao;
    }

}
